version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-network

  backend:
    build:
      context: ./order-api
      dockerfile: Dockerfile
    container_name: order-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - order-network

  frontend:
    build:
      context: ./order-ui
      dockerfile: Dockerfile
    container_name: order-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - order-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - order-network

networks:
  order-network:
    driver: bridge

volumes:
  postgres_data:
  jenkins_home:
